services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./www:/usr/share/nginx/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=casiopea.piwo.org
      - LETSENCRYPT_HOST=casiopea.piwo.org
    depends_on:
      - php

  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./www:/usr/share/nginx/html
    restart: unless-stopped 